on:
  push:
    branches:
      - dev
  workflow_dispatch:
  
jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest
    
    steps:
    - name: install ssh keys
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SERVER_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SERVER_HOST }} > ~/.ssh/known_hosts
    - name: connect and pull
      run: ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "cd /var/www/lanPage && git checkout dev && git pull && exit"
    - name: cleanup
      run: rm -rf ~/.ssh
