name: Deploy

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ssh-key: ${{ secrets.DEPLOY_KEY }}

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-interaction

    - name: Deploy to server
      run: |
        ssh -i ${{ secrets.DEPLOY_KEY }} ${{ secrets.SERVER_USERNAME}}@${{ secrets.SERVER_HOST}} "cd /var/www/lanPage && git pull && composer install --prefer-dist --no-dev --no-progress --no-interaction && php artisan migrate"
